name: counter_cli
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  etos: 0.0.1
  logging: any

dev_dependencies:
  lints: ^1.0.0
