name: etos_flutter
description: Helper widgets for Etos
version: 0.0.3
repository: https://github.com/SEGVeenstra/etos

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  etos: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
