name: etos
description: 
  An event-driven state management solution.
version: 0.0.1
repository: https://github.com/SEGVeenstra/etos
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  logging: ^1.0.2
  rxdart: ^0.27.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

